secrets:
  api-token: ""
  zone-name: ""

settings:
  ipv4:
    enabled: true # enabled ipv4 record (A)
    query:
      ## text format
      # url: https://ifconfig.me/ip
      # format: text

      ## json format
      # url: https://www.trackip.net/ip?json
      # format: json
      # key: IP

      ## key-value format
      url: https://1.1.1.1/cdn-cgi/trace
      format: kv
      separator: "="
      key: ip
  ipv6:
    enabled: true # enabled ipv6 record (AAAA)
    query:
      ## text format
      # url: https://api64.ipify.org/
      # format: text

      ## json format
      url: https://api64.ipify.org/?format=json
      format: json
      key: ip

      ## key-value format
      # url: https://https://[2606:4700:4700::1111]/cdn-cgi/trace
      # format: kv
      # separator: "="
      # key: ip
  ttl: ~ # record ttl in seconds

subdomains:
  - name: "@"
    enabled: true
    proxied: false
  - name: "grafana"
    enabled: true
    proxied: false

query:
  ipv4:

  ipv6:
    ## text format
    # url: https://ifconfig.me/ip
    # format: text

    ## json format
    # url: https://www.trackip.net/ip?json
    # format: json
    # key: IP

    ## key-value format
    url: https://1.1.1.1/cdn-cgi/trace
    format: kv
    separator: "="
    key: ip
