entities:
  - name: "@"
    enabled: false
  - name: "grafana2"
    mode-key: tunnel
    tunnel-name: pi10-llp
    tunnel-service: https://192.168.1.151

settings:
  ## Default entity properties.
  defaults:
    ## records mode: ip | ipv4 | ipv6 | tunnel.
    ## if not set, default is 'ip'
    mode-key: ip
    ## required if mode-key is 'tunnel'
    ## tunnel name
    tunnel-name: ''
    ## required if mode-key is 'tunnel'
    ## tunnel domain
    tunnel-domain: 'cfargotunnel.com'
    ## required if mode-key is 'tunnel'
    ## tunnel ingress path
    tunnel-path: ''
    ## required if mode-key is 'tunnel'
    ## tunnel ingress service
    tunnel-service: ''
    ## enabled all entities by default.
    ## if not set, default is false
    enabled: true
    ## enabled proxied for all entities by default.
    ## if not set, default is false
    proxied: true
    ## dns record ttl "string" ('0' mean 'auto').
    ## you must have suffix unit `h|m|s` (e.g. 30s)
    ## possible values are 0, 60-86400
    ## if not set, default is "0"
    ttl: "0"
  ## How to get static ipv4.
  ipv4:
    ## text format
    # url: https://ifconfig.me/ip
    # format: text
    ## key-value format
    # url: https://1.1.1.1/cdn-cgi/trace
    # format: kv
    # separator: "="
    # key: ip
    ## json format
    url: https://www.trackip.net/ip?json
    format: json
    key: IP
  ## How to get static ipv6.
  ipv6:
    ## text format
    # url: https://api64.ipify.org/
    # format: text
    ## key-value format
    # url: https://https://[2606:4700:4700::1111]/cdn-cgi/trace
    # format: kv
    # separator: "="
    # key: ip
    ## json format
    url: https://api64.ipify.org/?format=json
    format: json
    key: ip
  ## Tunnel settings
  tunnel:
    ## tunnel catchall service
    catchall-service: 'http_status:404'

secrets:
  ## Require permission
  ##   - Zone:Read
  ##   - DNS:Edit
  ##   - Cloudflare Tunnel:Edit
  ##   - Load Balancing: Monitors And Pools:Edit
  # api-token: ""

  ## Zone name
  # zone-name: ""

  ## Cloudflare account name,
  ## this can be either account name or accout id.
  ## if not set, default to first found account
  # account-name: ""

development: {}
