apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.name" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.configSpec | nindent 4 }}
